name: luna
dependencies:
  - python==3.11.3
  - pip==23.1.2
  - pip:
      - django==4.2.3
      - drf-yasg==1.21.6
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.2.2
      - django-cors-headers==4.1.0
      - pillow==10.0.0
      - flake8==6.0.0
      - gunicorn==20.1.0
      - phonenumbers==8.13.15